
(
//basic lookup
~asciiPalette =
   [["a","MaxV - FX 1.WAV"],
	["b","MaxV - FX 2.WAV"],
	["c","MaxV - FX 3.WAV"],
	["d","MaxV - FX 4.WAV"],
	["e","MaxV - FX 5.WAV"],
	["f","MaxV - FX 6.WAV"],
	["g","MaxV - FX 7.WAV"],
	["h","MaxV - FX 8.WAV"],
	["i","MaxV - FX 9.WAV"],
	["j","MaxV - FX 10.WAV"],
	["k","MaxV - FX 11.WAV",0.25],
	["l","MaxV - FX 12.WAV",0.25],
	[" ","silence.wav"]
];

~asciiPalette[9][2].postln;

)
